### ISSUE TITLE
Get-SfClient hangs on first run

### ISSUE THREAD

**Issue by ijjoyce** [citrix/ShareFile-PowerShell#15]
Every time I run Get-SfClient for the first time in a Powershell session, I get the following error:

Get-SfClient : A task was canceled.
At line:4 char:13
+ $sfClient = Get-SfClient -Name "C:\xxxxxxxx.sfps"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SfClient], TaskCanceledException
    + FullyQualifiedErrorId : System.Threading.Tasks.TaskCanceledException,ShareFile.Api.Powershell.GetSfClient

The script runs fine on the second execution.  Is there something I'm missing?  What would cause something like that to happen?

**Comment by virtualpete** [comment]
Is this in PowerShell or PowerShell ISE? 32-bit or 64-bit? What version of .NET and PowerShell? I remember seeing this in the past with certain version combinations.

**Comment by ijjoyce** [comment]
Ah yes!  Details would be nice, wouldn't they?

Powershell ISE 64-bit, Powershell version 4, .NET Framework 4.5.1 installed on Windows 7 SP1.  I'll test my script today from command line and see if that performs differently, but I feel like I remember doing that and it didn't work then either.

Thanks!

**Comment by ijjoyce** [comment]
I confirmed that the script doesn't complete on the first run regardless of whether it's launched from command line or in Powershell ISE.  I could test a work around by just placing two Get-SfClient statements back to back in the script, but that seems like it wouldn't be the most efficient and reliable method.

**Comment by apikeith** [comment]
Hi, I was wondering when the first version of the SDK you installed was?  There was an issue with an earlier version of the SDK with Get-SfClient and a full uninstall and reinstall of the latest was needed in order to fix it.

**Comment by ijjoyce** [comment]
I've got version 1.5 of the Sharefile PowerShell SnapIn and source.  This was the first version I installed and it was installed last week.

**Comment by ijjoyce** [comment]
Just wanted to check in and see if there were any thoughts on this?  Is there anything I should try?

**Comment by virtualpete** [comment]
The latest release is 1.82. We didn't make it clear on the download page, but the part that is in beta is the installer. You should grab the latest compiled binaries if you don't want to use the beta installer.

**Comment by ijjoyce** [comment]
That did the trick!  Thank you for your help.  I appreciate the improved progress bar, as well!
