### ISSUE TITLE
FileID not found

### ISSUE THREAD

**Issue by je7je** [citrix/ShareFile-PowerShell#19]
Where/how do we identify the FileID? We are told how to label it but not where to pull it from.

**Comment by SFSDK** [comment]
You can do a get by path or a search to get the file and then you'll have the fileID.  You can also do get Children if you have the parent fileID.  You can find more API endpoints at api.sharefile.com, you just have to modify them to PowerShell format.

**Comment by rgmills** [comment]
@je7je Going to go ahead and close this issue. Let us know if you are still running into issues.
