### ISSUE TITLE
New To Github

### ISSUE THREAD

**Issue by rwinhold** [citrix/ShareFile-PowerShell#22]
Not sure where else to post this.  I'm new to Github (thanks for the quick responses on my previous question) so I'm still trying to find my way around here.

So, is there a general discussion area specific to Sharefile?  Or even a non-specific discussion area?  I have a question which isn't related to an issue with the code so this probably isn't an appropriate area to ask...

Thanks

**Comment by apikeith** [comment]
Hi, 

You can use the developer forum at http://devforum.sharefile.com for development related questions or https://community.sharefilesupport.com for any other ShareFile related questions.

--Keith

**Comment by rwinhold** [comment]
Thanks Keith!
